#!/usr/bin/env bash
# Render ~/.aws/config for this host's two Roles Anywhere profiles.
#
# Hand-authored profiles are how a Hostinger rebuild ends up pointing at
# Akamai's certificate filenames: the runbook says "generate a new key, do not
# reuse the old one" and then shows a config block containing
# trupryce-data-platform-vps.pem, and the second instruction is the one that
# gets copied.
#
# Everything host-specific already lives in infra/.env, so derive from it. There
# is nothing to keep in sync by hand.
#
# Writes no credential. `credential_process` names a command; the proof is the
# certificate, and the AWS CLI runs the helper on demand.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
infra_dir="$(cd "$script_dir/.." && pwd)"
compose_environment_file="${COMPOSE_ENV_FILE:-$infra_dir/.env}"
aws_config="${AWS_CONFIG_FILE:-$HOME/.aws/config}"
signing_helper="${SIGNING_HELPER_PATH:-/usr/local/bin/aws_signing_helper}"
region="${AWS_REGION:-us-east-1}"

die() { printf 'install-aws-profiles: %s\n' "$*" >&2; exit 2; }
info() { printf 'install-aws-profiles: %s\n' "$*" >&2; }

[[ -r "$compose_environment_file" ]] || die "cannot read $compose_environment_file"

read_configuration_value() {
    local line
    line="$(grep -E "^$1=" "$compose_environment_file" | tail -n 1 || true)"
    printf '%s' "${line#*=}"
}

certificate="$(read_configuration_value TRUPRYCE_AWS_CERTIFICATE)"
private_key="$(read_configuration_value TRUPRYCE_AWS_PRIVATE_KEY)"
trust_anchor="$(read_configuration_value TRUPRYCE_AWS_TRUST_ANCHOR_ARN)"
backup_profile_arn="$(read_configuration_value TRUPRYCE_AWS_PROFILE_ARN)"
backup_role_arn="$(read_configuration_value TRUPRYCE_AWS_ROLE_ARN)"

# The data profile is the other half of the same identity. It is host-specific
# in exactly the same way, so it is configured here rather than by hand.
data_profile_arn="$(read_configuration_value TRUPRYCE_AWS_DATA_PROFILE_ARN)"
data_role_arn="$(read_configuration_value TRUPRYCE_AWS_DATA_ROLE_ARN)"

for name in TRUPRYCE_AWS_CERTIFICATE TRUPRYCE_AWS_PRIVATE_KEY \
            TRUPRYCE_AWS_TRUST_ANCHOR_ARN TRUPRYCE_AWS_PROFILE_ARN TRUPRYCE_AWS_ROLE_ARN \
            TRUPRYCE_AWS_DATA_PROFILE_ARN TRUPRYCE_AWS_DATA_ROLE_ARN; do
    [[ -n "$(read_configuration_value "$name")" ]] || die "$compose_environment_file does not define $name"
done

for path in "$certificate" "$private_key"; do
    [[ -r "$path" ]] || die "cannot read $path (run install-certificate-identity.sh first)"
done
[[ -x "$signing_helper" ]] || die "missing $signing_helper (run install-signing-helper.sh first)"

# Refuse to write a config that names a certificate this host does not use.
# That is the copy/paste failure this script exists to prevent.
certificate_subject="$(openssl x509 -in "$certificate" -noout -subject 2>/dev/null || true)"
info "certificate subject: ${certificate_subject:-unknown}"

mkdir -p "$(dirname "$aws_config")"
if [[ -e "$aws_config" ]]; then
    backup="$aws_config.$(date -u +%Y%m%d%H%M%S).bak"
    cp -p "$aws_config" "$backup"
    info "existing config preserved at $backup"
fi

umask 077
cat > "$aws_config" <<CONFIG
# Generated by infra/scripts/install-aws-profiles.sh. Do not hand-edit.
# Derived from $compose_environment_file; change values there and re-run.
#
# No credential is stored here. credential_process names a command; the proof of
# identity is the workload certificate, and the AWS CLI exchanges it on demand.

[profile trupryce-data-vps]
region = $region
credential_process = $signing_helper credential-process --certificate $certificate --private-key $private_key --trust-anchor-arn $trust_anchor --profile-arn $data_profile_arn --role-arn $data_role_arn

[profile trupryce-backup]
region = $region
credential_process = $signing_helper credential-process --certificate $certificate --private-key $private_key --trust-anchor-arn $trust_anchor --profile-arn $backup_profile_arn --role-arn $backup_role_arn
CONFIG
chmod 0600 "$aws_config"

info "wrote $aws_config (mode 0600)"
grep -c 'aws_access_key_id\|aws_secret_access_key' "$aws_config" >/dev/null 2>&1 \
    && die "generated config unexpectedly contains a stored key" || true
info "profiles: trupryce-data-vps, trupryce-backup"
