#!/usr/bin/env bash
# Install the certificate directory's permission contract and identity file.
#
# Two things the PostgreSQL container needs that no image can carry:
#
#   1. The workload key readable by the container's postgres user without being
#      world-readable, which is a group with a fixed numeric GID.
#   2. A non-secret identity file the signing wrapper can read when pgBackRest's
#      asynchronous archive worker execs it with a cleaned environment.
#
# The second exists because the environment variables Compose sets reach a
# `docker exec` and a `stanza-create` but not the async worker, so an
# environment-only wrapper authenticates for every check an operator runs by
# hand and fails exactly where archiving happens.
#
# Values are DERIVED from infra/.env, the reviewed non-secret host configuration,
# so there is one place to change an ARN and no duplicate to drift.
#
# This file holds no secret. The cipher passphrase, the Bitwarden token, and AWS
# credentials are all deliberately absent: temporary credentials are exchanged
# per invocation from the certificate, and the passphrase comes from Bitwarden.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
infra_dir="$(cd "$script_dir/.." && pwd)"
compose_environment_file="${COMPOSE_ENV_FILE:-$infra_dir/.env}"

die() { printf 'install-certificate-identity: %s\n' "$*" >&2; exit 2; }
info() { printf 'install-certificate-identity: %s\n' "$*" >&2; }

[[ "$(id -u)" -eq 0 ]] || die "must run as root to set ownership under the certificate directory"
[[ -r "$compose_environment_file" ]] || die "cannot read $compose_environment_file"

read_configuration_value() {
    local line
    line="$(grep -E "^$1=" "$compose_environment_file" | tail -n 1 || true)"
    printf '%s' "${line#*=}"
}

certificate_directory="$(read_configuration_value TRUPRYCE_AWS_CERTIFICATE_DIR)"
certificate_directory="${certificate_directory:-/etc/trupryce/aws}"
certificate_gid="$(read_configuration_value TRUPRYCE_AWS_GID)"
certificate_gid="${certificate_gid:-2000}"

# Exactly the variables the signing wrapper requires, and nothing else.
IDENTITY_KEYS=(
    TRUPRYCE_AWS_CERTIFICATE
    TRUPRYCE_AWS_PRIVATE_KEY
    TRUPRYCE_AWS_TRUST_ANCHOR_ARN
    TRUPRYCE_AWS_PROFILE_ARN
    TRUPRYCE_AWS_ROLE_ARN
)

# Refuse to write a file that would leave the wrapper failing at runtime.
for key in "${IDENTITY_KEYS[@]}"; do
    value="$(read_configuration_value "$key")"
    [[ -n "$value" ]] || die "$compose_environment_file does not define $key"
    printf -v "resolved_$key" '%s' "$value"
done

# A secret reaching this file would be world-visible to anything in the
# certificate group, so refuse the names that must never appear.
for forbidden in PGBACKREST_CIPHER_PASS PGBACKREST_REPO1_CIPHER_PASS \
                 BWS_ACCESS_TOKEN AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN; do
    [[ " ${IDENTITY_KEYS[*]} " == *" $forbidden "* ]] \
        && die "refusing to write $forbidden into the identity file"
done

[[ -d "$certificate_directory" ]] || die "certificate directory does not exist: $certificate_directory"

certificate_path="$(read_configuration_value TRUPRYCE_AWS_CERTIFICATE)"
private_key_path="$(read_configuration_value TRUPRYCE_AWS_PRIVATE_KEY)"
for required_file in "$certificate_path" "$private_key_path"; do
    [[ -f "$required_file" ]] || die "missing certificate material: $required_file"
done

if getent group "$certificate_gid" >/dev/null; then
    info "certificate group $certificate_gid present ($(getent group "$certificate_gid" | cut -d: -f1))"
else
    groupadd --gid "$certificate_gid" trupryce-certificates
    info "created group trupryce-certificates ($certificate_gid)"
fi

identity_file="$certificate_directory/identity.env"
umask 027
{
    printf '# Generated by infra/scripts/install-certificate-identity.sh. Do not hand-edit.\n'
    printf '# Derived from %s; change values there and re-run.\n' "$compose_environment_file"
    printf '#\n'
    printf '# Non-secret: certificate paths and ARNs only. Read by the pgBackRest S3\n'
    printf '# signing wrapper because the asynchronous archive worker execs it with a\n'
    printf '# cleaned environment. Contains no passphrase, token, or AWS credential.\n'
    for key in "${IDENTITY_KEYS[@]}"; do
        name="resolved_$key"
        printf '%s=%s\n' "$key" "${!name}"
    done
} > "$identity_file"

# The permission contract, applied to every file the container reads. The key
# is group-readable and never world-readable; the directory must be group
# traversable or the key's own group bit is unreachable.
owner="$(stat -c '%u' "$certificate_directory")"
chown "$owner:$certificate_gid" "$identity_file"
chmod 0640 "$identity_file"

chgrp "$certificate_gid" "$certificate_directory" "$certificate_path" "$private_key_path"
chmod 0750 "$certificate_directory"
chmod 0640 "$private_key_path"
chmod 0644 "$certificate_path"

if [[ -f "$certificate_directory/root-ca.pem" ]]; then
    chgrp "$certificate_gid" "$certificate_directory/root-ca.pem"
    chmod 0644 "$certificate_directory/root-ca.pem"
fi

info "installed $identity_file"
stat -c '  %n mode=%a owner=%U group=%g' \
    "$certificate_directory" "$identity_file" "$private_key_path" "$certificate_path"

# Fail closed on the one mistake that matters: a world-readable private key.
key_mode="$(stat -c '%a' "$private_key_path")"
(( (8#$key_mode & 007) == 0 )) || die "private key is world-accessible: $key_mode"
